import type { Event } from "./types";

// Sample data - in a real app, this would come from a database
export const initialEvents: Event[] = [
  {
    id: "1",
    title: "Tech Conference 2025",
    date: "2025-06-15",
    time: "09:00",
    location: "San Francisco Convention Center",
    description:
      "Annual technology conference featuring the latest innovations and industry speakers. This premier event brings together thought leaders, innovators, and technology enthusiasts from around the globe. Attendees will experience hands-on workshops, keynote presentations from industry pioneers, networking opportunities with like-minded professionals, and exclusive previews of upcoming technologies. The conference will cover a wide range of topics including artificial intelligence, blockchain, cloud computing, cybersecurity, data science, and emerging technologies. Whether you're a seasoned professional or just starting your tech journey, this conference offers valuable insights and connections to help advance your career and knowledge. Don't miss this opportunity to be part of the most anticipated tech event of the year!",
    attendees: 1200,
    status: "upcoming",
    sectionType: "Cover page",
    target: 18,
    limit: 5,
    reviewer: "Eddie Lake",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "2",
    title: "Music Festival",
    date: "2025-07-22",
    time: "16:00",
    location: "Central Park",
    description:
      "Three-day music festival with top artists from around the world.",
    attendees: 5000,
    status: "upcoming",
    sectionType: "Table of contents",
    target: 29,
    limit: 24,
    reviewer: "Eddie Lake",
  },
  {
    id: "3",
    title: "Charity Gala",
    date: "2025-05-10",
    time: "19:00",
    location: "Grand Hotel Ballroom",
    description:
      "Annual fundraising event for local charities with dinner and silent auction.",
    attendees: 350,
    status: "completed",
    sectionType: "Executive summary",
    target: 10,
    limit: 13,
    reviewer: "Eddie Lake",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "4",
    title: "Product Launch",
    date: "2025-08-05",
    time: "10:00",
    location: "Downtown Innovation Hub",
    description:
      "Exclusive launch event for our newest product line with demonstrations and networking.",
    attendees: 200,
    status: "upcoming",
    sectionType: "Technical approach",
    target: 27,
    limit: 23,
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: "5",
    title: "Workshop Series",
    date: "2025-04-18",
    time: "13:00",
    location: "Community Center",
    description:
      "Weekly workshop series covering various topics in professional development.",
    attendees: 75,
    status: "completed",
    sectionType: "Design",
    target: 2,
    limit: 16,
    reviewer: "Jamik Tashpulatov",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "6",
    title: "Annual Conference",
    date: "2025-09-22",
    time: "08:00",
    location: "Metropolitan Convention Center",
    description:
      "Our flagship annual conference bringing together industry leaders and innovators.",
    attendees: 1500,
    status: "upcoming",
    sectionType: "Capabilities",
    target: 20,
    limit: 8,
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: "7",
    title: "Developer Meetup",
    date: "2025-06-30",
    time: "18:30",
    location: "Tech Hub Downtown",
    description:
      "Monthly meetup for developers to network and share knowledge.",
    attendees: 120,
    status: "upcoming",
    sectionType: "Integration with existing systems",
    target: 19,
    limit: 21,
    reviewer: "Jamik Tashpulatov",
  },
  {
    id: "8",
    title: "Leadership Summit",
    date: "2025-08-15",
    time: "09:00",
    location: "Executive Conference Center",
    description:
      "Exclusive summit for C-level executives focusing on future trends.",
    attendees: 75,
    status: "completed",
    sectionType: "Innovation and Advantages",
    target: 25,
    limit: 26,
    reviewer: "Unassigned",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "9",
    title: "Industry Expo",
    date: "2025-10-05",
    time: "10:00",
    location: "Exhibition Hall",
    description:
      "Largest industry expo showcasing the latest products and services.",
    attendees: 3000,
    status: "upcoming",
    sectionType: "Technical content",
    target: 7,
    limit: 23,
    reviewer: "Unassigned",
  },
  {
    id: "10",
    title: "AI Symposium",
    date: "2025-07-12",
    time: "09:30",
    location: "Science Center",
    description:
      "Symposium on the latest advancements in artificial intelligence and machine learning.",
    attendees: 450,
    status: "completed",
    sectionType: "Narrative",
    target: 30,
    limit: 28,
    reviewer: "Unassigned",
  },
].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()); // Sort by date, newest first
